### ISSUE TITLE
SelectTree Message

### ISSUE THREAD

**Issue by d3xter** [kirchner/elm-selectize#12]
Right now, SelectTree Message is emitted every time the User types in a Character or removes one.

I was under the impression that this Message will only be sent, if the User either selects an Item or clears the Selection.
Is the current behaviour desired?

**Comment by kirchner** [comment]
I think these messages should be `SelectTree Nothing`. The idea was to clear the selection when the user changes the query. So, that's kind of the intended behaviour. But I'm not sure actually if that is what one wants in every situation.
