### ISSUE TITLE
CSS class container collides with bootstrap

### ISSUE THREAD

**Issue by bodison** [kirchner/elm-selectize#3]
Is it possible to change the name of the CSS class *container*?

I want to use bootstrap which uses the same name for its container class.

**Comment by kirchner** [comment]
Are you using version 2.0.5? You should be able to change the container css class by adjusting your viewConfig. Something like this should work

```elm
viewConfig : Selectize.ViewConfig a
viewConfig =
    Selectize.viewConfig
        { container =
            [ Attributes.class "some-other-container-class-name" ]
        ...
        }
```
