### ISSUE TITLE
Print page shows menu as a gray box

### ISSUE THREAD

**Issue by bodison** [kirchner/elm-selectize#4]
When printing a page the selectize menu shows up as a gray box occluding other content.

Please add this CSS!
`
@media print {
    div.selectize__menu {
        display: none;
    }
}`

**Comment by kirchner** [comment]
When using selectize in your own application, you should be able to apply these css things by adjusting the viewConfig.  I'm also not sure if one can do these media queries inline?  Or are you referring to the demo?  If so, feel free to open a pull request with the changes, you think are appropriate! :)
