### ISSUE TITLE
multiselectize functionality in demo

### ISSUE THREAD

**Issue by mordrax** [kirchner/elm-selectize#5]
Trying to find the source behind the multi selectize in the demo but unable to. I thought it would be part of the demo/demo.elm, all I found though was this issue saying that it isn't implemented in this repo: https://github.com/kirchner/elm-selectize/issues/2 dating back to august.

So is the functionality shown in the demo implemented in the repo? Confused... if yes, how do I do multi selection? ( as on further investigation, there are commits related to it! :)

**Comment by kirchner** [comment]
@mordrax yes, the multiselectize implementation is in the master branch. :) I have not decided yet if the api is good as it is now, so it is not published, yet.
