### ISSUE TITLE
Request to update elm-package dependency, list-extra.

### ISSUE THREAD

**Issue by trippingtarballs** [kirchner/elm-selectize#6]
https://github.com/kirchner/elm-selectize/blob/2d687439054b713abe62be53f6ed863ac37534c4/elm-package.json#L16

Would it be possible to update the constraints for, `elm-community/list-extra`? Use of `kirchner/elm-selectize` requires that I downgrade my version of `list-extra`.

**Comment by kirchner** [comment]
@trippingtarballs i updated the dependency to the newest version and published it on packages.elm-lang.org
