### ISSUE TITLE
multi-select?

### ISSUE THREAD

**Issue by nathanbraun** [kirchner/elm-selectize#7]
Have you thought more about the multi-select API?  Would love to be able to do what's on the demo now.

**Comment by kirchner** [comment]
Hi! I am not sure if the multiselect widget is too specialized for a package, and whether the api i chose is good. There are quite a few different UX choices (which are all reasonable depending on the situation) one can make and I don't know yet how to incorporate them in a good way. So it's probably best if you just copy the code to your project and adjust it to your needs, if you need this multi select dropdown. Does this help?
